name: jbl_pills_reminder_app
description: "jbl pills reminder app"
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.4
  device_info_plus: ^11.2.1
  http: ^1.3.0
  camera: ^0.11.0+2
  iconify_flutter: ^0.0.7
  font_awesome_flutter: ^10.8.0
  toastification: ^3.0.1
  flutter_timezone: ^4.0.0
  table_calendar: ^3.1.3
  fluentui_system_icons: ^1.1.271
  smooth_page_indicator: ^1.2.0+3
  gap: ^3.0.1
  get: ^5.0.0-release-candidate-9.3.2
  google_fonts: ^6.2.1
  http_status_code: ^0.0.2
  package_info_plus: ^8.1.3
  searchfield: ^1.2.2
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  flutter_foreground_task: ^8.17.0
  alarm: ^5.0.3
  internet_connection_checker_plus: ^2.7.0
  path_provider: ^2.1.5
  fluttertoast: ^8.2.11
  clipboard: ^0.1.3
  open_file: ^3.5.10
  awesome_notifications: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/img/


flutter_native_splash:
  color: "#ffffff"
  image: assets/app_logo.jpeg
  android_12:
    image: assets/app_logo.jpeg
    icon_background_color: 
