name: jbl_pills_reminder_app
description: "jbl pills reminder app"
publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: ^3.6.1

dependencies:
  alarm: ^5.1.4
  awesome_notifications: ^0.10.1
  clipboard: ^0.1.3
  device_info_plus: ^11.3.3
  dio: ^5.8.0+1
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_foreground_task: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  fluttertoast: ^8.2.12
  gap: ^3.0.1
  get: ^5.0.0-release-candidate-9.3.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  http_status_code: ^0.0.2
  icons_launcher: ^3.0.1
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  open_file: ^3.5.10
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  searchfield: ^1.2.6
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  table_calendar: ^3.2.0
  toastification: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/img/
    - assets/resources/
    - assets/sound/


flutter_native_splash:
  color: "#ffffff"
  image: assets/app_logo.jpeg
  android_12:
    image: assets/app_logo.jpeg
    icon_background_color:

icons_launcher:
  image_path: "assets/app_logo.jpeg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
